language: python
python:
 - "3.4"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq librrd-dev

install:
 - pip install -r requirements.txt
 - ./manage.py migrate
 - sleep 1
 - cd collect_server
 - python3 run_server.py &
 - sleep 1
 - python3 run_listener.py & 
 - sleep 1
 - cd ../collect_client
 - python3 run_client.py & 
 - sleep 10
 - cd ..

script:
 - ./manage.py test

addons:
  hosts:
    - test.com

